version: "3.8"

services:
  app:
    build: .
    container_name: inventory-app
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://mongodb:27017/inventar
      - REDIS_URL=redis://redis:6379
      - BASE_URL=https://inventar.maximiliangruendinger.de #alle öffentliche subdomains
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    # Der Tunnel-Name 'homeserver' muss zu deiner credentials.json passen
    command: tunnel run homeserver
    volumes:
      - ./config.yml:/etc/cloudflared/config.yml
      - ./credentials.json:/etc/cloudflared/credentials.json
    depends_on:
      - app

volumes:
  mongo_data: